// <auto-generated />
namespace LeaveSystem.DomainModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class new8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new8));
        
        string IMigrationMetadata.Id
        {
            get { return "202110151147021_new8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
